name: thrifty_cab
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  audioplayers: ^0.20.1
  cached_network_image: ^3.1.0
  country_code_picker: ^2.0.2
  dropdown_below: ^1.0.0
  easy_localization: ^3.0.0
  flutter:
    sdk: flutter
  flutter_animated_dialog: null
  flutter_polyline_points: ^1.0.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.0.3
  geolocator: ^7.1.1
  google_maps_flutter: ^2.0.9
  http: ^0.13.4
  image_cropper: ^1.4.1
  image_picker: ^0.8.4
  intl: ^0.17.0
  location: ^4.3.0
  path_provider: ^2.0.4
  photo_view: null
  place_picker: ^0.9.20-nullsafety
  provider: ^6.0.0
  razorpay_flutter: ^1.2.6
  shared_preferences: ^2.0.7
  shimmer: ^2.0.0
dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.jpg"
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo/
    - assets/icons/
    - assets/json/
    - assets/translations/
    - assets/sounds/
    - assets/json/taxi/
